# clouddeploy.yaml

apiVersion: deploy.cloud.google.com/v1alpha1
kind: Pipeline
metadata:
  name: my-python-app-pipeline
spec:
  stages:
    - name: "deploy"
      targets:
        - name: "my-cloud-run-target"   # Target environment (Cloud Run in this case)
      release:
        name: "my-python-app-release"  # Release name for the rollout
        description: "My Python app release rollout"
        resources:
          - name: "my-python-app-service"  # Cloud Run service to be deployed
          - type: "cloudrun"  # Cloud Run service type

  # Define a rollout configuration
  rollout:
    rolloutStrategy: "STANDARD"  # Can be either "STANDARD" or "CANARY"
    rolloutStart:
      releaseName: "my-python-app-release"
      deployTo:
        environments:
          - "prod"  # Target environment (prod or other environments)
        rolloutPolicy:
          maxConcurrent: 1   # Maximum number of concurrent deployments
          maxFailed: 1       # Maximum number of failed rollouts
          successThreshold: 1  # Minimum number of successful rollouts
