# cloudbuild.yaml

steps:
  # Step 1: Check if the Delivery Pipeline exists, and create it if it doesn't
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'Check and Create Pipeline'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        PIPELINE_NAME="my-python-app-pipeline"
        REGION="us-central1"
        PROJECT="enhub-cloud-interns"
        
        # Check if the delivery pipeline exists
        if ! gcloud deploy delivery-pipelines describe $PIPELINE_NAME --region=$REGION --project=$PROJECT; then
          echo "Pipeline does not exist. Creating pipeline..."
          gcloud deploy delivery-pipelines create $PIPELINE_NAME --region=$REGION --project=$PROJECT
        else
          echo "Pipeline $PIPELINE_NAME already exists."
        fi

  # Step 2: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/enhub-cloud-interns/my-python-app', '.']

  # Step 3: Push Docker Image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/enhub-cloud-interns/my-python-app']

  # Step 4: Create a Release in Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    args:
      - 'gcloud'
      - 'deploy'
      - 'releases'
      - 'create'
      - 'my-python-app-release'
      - '--images=gcr.io/enhub-cloud-interns/my-python-app=gcr.io/enhub-cloud-interns/my-python-app'
      - '--delivery-pipeline=my-python-app-pipeline'
      - '--region=us-central1'

  # Step 5: Trigger the Rollout in Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    args:
      - 'gcloud'
      - 'deploy'
      - 'rollouts'
      - 'create'
      - '--release=my-python-app-release'
      - '--delivery-pipeline=my-python-app-pipeline'
      - '--region=us-central1'

options:
  logging: CLOUD_LOGGING_ONLY  # Log to Cloud Logging only (no bucket required)

# Substitutions
substitutions:
  _SERVICE_ACCOUNT: "1064351983714-compute@developer.gserviceaccount.com"

# Timeout for build (optional)
timeout: "1200s"
