apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: amjad-pipeline
  annotations:
    clouddeploy.googleapis.com/location: asia-east1
description: Cloud Deploy pipeline for Amjad service
serialPipeline:
  stages:
    - targetId: amjad-deploy-target-1

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: amjad-deploy-target-1
  annotations:
    clouddeploy.googleapis.com/location: asia-east1
description: Cloud Run target for Amjad service in asia-east1
run:
  location: projects/enhub-cloud-interns/locations/asia-east1
