apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: amjad-pipeline
  region: asia-east1
spec:
  stages:
  - targetId: amjad-target
    profiles: []
  targets:
  - id: amjad-target
    run:
      location: asia-east1
      service: amjad-cloudrun-service
