# cloudbuild.yaml

steps:
  # Step 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/enhub-cloud-interns/my-python-app', '.']

  # Step 2: Push Docker Image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/enhub-cloud-interns/my-python-app']

  # Step 3: Create a Release in Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    args:
      - 'gcloud'
      - 'deploy'
      - 'releases'
      - 'create'
      - '--images=gcr.io/enhub-cloud-interns/my-python-app'  # Correct argument for specifying image
      - '--delivery-pipeline=my-python-app-pipeline'       # Correct argument for pipeline

  # Step 4: Trigger the Rollout in Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    args:
      - 'gcloud'
      - 'deploy'
      - 'rollouts'
      - 'create'
      - '--release=my-python-app-release'
      - '--delivery-pipeline=my-python-app-pipeline'
      - '--region=us-central1'

options:
  logging: CLOUD_LOGGING_ONLY  # Log to Cloud Logging only (no bucket required)

# Substitutions
substitutions:
  _SERVICE_ACCOUNT: "1064351983714-compute@developer.gserviceaccount.com"

# Timeout for build (optional)
timeout: "1200s"
